# Generated by Django 2.2.4 on 2020-10-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
