# Generated by Django 2.2.4 on 2020-10-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showApp', '0002_auto_20201012_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
