# Generated by Django 2.2.4 on 2020-10-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showApp', '0003_auto_20201012_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.DateField(),
        ),
    ]
